apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: deploy02-inatel-centos7
  namespace: fibre-ng
spec:
  selector:
    matchLabels:
      app: centos7
  replicas: 1
  template:
    metadata:
      labels:
        app: centos7
    spec:
      containers:
      - name: centos7
        image: docker.io/centos/tools:latest
        command:
        - /sbin/init
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: inatel-edge1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy02-ufba-centos7
  namespace: fibre-ng
spec:
  selector:
    matchLabels:
      app: centos7
  replicas: 1
  template:
    matadata:
      labels:
        app: centos7
      spec:
        containers:
        - name: centos7
          image: docker.io/centos/tools:latest
          command:
          - /sbin/init
          imagePullPolicy: IfNotPresent
        restartPolicy: Always
        nodeSelector:
          kubernetes.io/hostname: ufba-edge1